### ISSUE TITLE
Getting playwright error

### ISSUE THREAD

**Issue by Nishchal-G** [sushil-rgb/YellowPage-scraper#1]
Hi I was trying your code, I'm getting error in scraper.py. (I'm using jupyter notebook). Below is the complete error

---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
Cell In[5], line 15
     12         data = yellowPages(p, make_headless)
     13         return data
---> 15 print(yellow())
     17 total_time = round(time.time()-start_time, 2)
     18 time_in_secs = round(total_time)

Cell In[5], line 11, in yellow()
     10 def yellow():
---> 11     with sync_playwright() as p:        
     12         data = yellowPages(p, make_headless)
     13         return data

File c:\Users\106141\AppData\Local\Programs\Python\Python38\lib\site-packages\playwright\sync_api\_context_manager.py:44, in PlaywrightContextManager.__enter__(self)
     42             self._own_loop = True
     43         if self._loop.is_running():
---> 44             raise Error(
     45                 """It looks like you are using Playwright Sync API inside the asyncio loop.
     46 Please use the Async API instead."""
     47             )
     49         # In Python 3.7, asyncio.Process.wait() hangs because it does not use ThreadedChildWatcher
     50         # which is used in Python 3.8+. This is unix specific and also takes care about
     51         # cleaning up zombie processes. See https://bugs.python.org/issue35621
...
     56             and isinstance(asyncio.get_child_watcher(), asyncio.SafeChildWatcher)
     57         ):

Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.

**Comment by sushil-rgb** [comment]
Hey there, it looks like you have added an asynchronous function probably asyncio from line 42. The script is pure synchronous, however, there's an asynchronous approach using a playwright, I would have to create a separate branch for asynchronous tasks. Hope this helps. 
Edit: If you're using Jupyter then it's from the local server that's why you are getting an error. I may be wrong but probably this is it. Try this code in vs code and let me know if you get the error or not.

**Comment by Nishchal-G** [comment]
Hi @sushil-rgb thanks for the reply. I tried running it in vs code and its working fine
