### ISSUE TITLE
Sync API vs. Async API

### ISSUE THREAD

**Issue by mannycorrao** [sushil-rgb/YellowPage-scraper#2]
Hello:

I'm getting the following error and need help resolving the issue.

Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.

Thanks,

Manny

**Comment by sushil-rgb** [comment]
Hello mannycorrao,
It seems you're using asyncio loop library, the script is pure synchronous, I suggest you run the script from vs code, the code will run

**Comment by mannycorrao** [comment]
Hello:

Thanks for the prompt reply.

I'm running the script in Spyder: I'm guessing you mean I need to run it using Visual Studio Code: correct?

Thanks,

Manny

**Comment by sushil-rgb** [comment]
Yes Manny, try running it on Visual Studio Code: If the issue still persists, please let me know.

**Comment by mannycorrao** [comment]
Will do. Thanks again.

Manny.

**Comment by mannycorrao** [comment]
Hello:

It runs fine in Visual Studio Code:; however, I discovered I can run it using the PowerShell terminal as well.

Thanks again for the help.

Manny

**Comment by mannycorrao** [comment]
Hello:

It runs fine in Visual Studio Code:; however, I discovered I can run it using the PowerShell terminal found in anaconda as well.

Thanks again for the help.

Manny
